@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.example.examplemod.mixins;
import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;